/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sDOB = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sSubject = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        sRead = new javax.swing.JCheckBox();
        sWrite = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        sMale = new javax.swing.JRadioButton();
        sFemale = new javax.swing.JRadioButton();
        sSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sAddress = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        eMail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 464, -1));

        jLabel2.setText("Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 108, 50, -1));
        getContentPane().add(sName, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 105, 301, -1));

        jLabel3.setText("Date   :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, -1, -1));
        getContentPane().add(sDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 139, 301, -1));

        jLabel4.setText("Address :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 227, -1, -1));

        jLabel5.setText("Subject :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 281, -1, -1));

        sSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selected--", "JEE", "PHP", "GD", "DDD" }));
        getContentPane().add(sSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 278, -1, -1));

        jLabel6.setText("Hobby :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 320, -1, -1));

        sRead.setText("Reading");
        getContentPane().add(sRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 318, -1, -1));

        sWrite.setText("Writing");
        getContentPane().add(sWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 318, -1, -1));

        jLabel7.setText("Gender :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 358, -1, -1));

        buttonGroup1.add(sMale);
        sMale.setText("Male");
        getContentPane().add(sMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 356, -1, -1));

        buttonGroup1.add(sFemale);
        sFemale.setText("Female");
        getContentPane().add(sFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 356, -1, -1));

        sSubmit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sSubmit.setText("Submit");
        sSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sSubmitMouseClicked(evt);
            }
        });
        getContentPane().add(sSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 400, -1, -1));

        sAddress.setColumns(20);
        sAddress.setRows(5);
        jScrollPane1.setViewportView(sAddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 218, 303, 40));

        jLabel8.setText("Email :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 182, -1, -1));
        getContentPane().add(eMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 179, 301, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sSubmitMouseClicked
        // TODO add your handling code here:

        String name = sName.getText();
        String date = sDOB.getDate().toString();

        String address = sAddress.getText();
        String subject = sSubject.getSelectedItem().toString();

        List<String> hobby = new ArrayList<>();
        if (sRead.isSelected()) {
            hobby.add("Reading");
        }
        if (sWrite.isSelected()) {
            hobby.add("Writing");
        }

        String gender = " ";
        if (sMale.isSelected()) {
            gender = "Male";
        } else if (sFemale.isSelected()) {
            gender = "Female";
        }

        String email = eMail.getText().trim();
        String pattern = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";

        try {

            PrintWriter write = new PrintWriter("Student.txt");

            if (email.matches(pattern)) {

                write.print("  Name      : " + name + "\n");
                write.print("  Date      : " + date + "\n");
                write.print("  Email     : " + email + "\n");
                write.print("  Address   : " + address + "\n");
                write.print("  Subject   : " + subject + "\n");
                write.print("  Hobby     : " + hobby + "\n");
                write.print("  Gender    : " + gender);
                write.close();

                JOptionPane.showMessageDialog(rootPane, "Congratulation \n\n" + "Submit is Successfull");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Congratulation \n\n" + "Email is Invalied");
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sSubmitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField eMail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea sAddress;
    private com.toedter.calendar.JDateChooser sDOB;
    private javax.swing.JRadioButton sFemale;
    private javax.swing.JRadioButton sMale;
    private javax.swing.JTextField sName;
    private javax.swing.JCheckBox sRead;
    private javax.swing.JComboBox<String> sSubject;
    private javax.swing.JButton sSubmit;
    private javax.swing.JCheckBox sWrite;
    // End of variables declaration//GEN-END:variables
}
