/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class StudentForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentForm
     */
    public StudentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtPhone = new javax.swing.JTextField();
        txtName1 = new javax.swing.JTextField();
        txtFather = new javax.swing.JTextField();
        txtMother1 = new javax.swing.JTextField();
        txtFemale = new javax.swing.JRadioButton();
        txtMale = new javax.swing.JRadioButton();
        txtDate = new com.toedter.calendar.JDateChooser();
        txtSubject = new javax.swing.JComboBox<>();
        txtGame = new javax.swing.JCheckBox();
        txtRead = new javax.swing.JCheckBox();
        txtWrite = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Form");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Mother's Name :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Hobby :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Father's Name :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Name :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Phone No :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Gender :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Date of Birth :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Subject :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 450));

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 100, 50));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 320, -1));

        txtName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 320, -1));

        txtFather.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFather.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 320, -1));

        txtMother1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMother1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtMother1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 320, -1));

        buttonGroup1.add(txtFemale);
        txtFemale.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFemale.setText("Female");
        jPanel1.add(txtFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        buttonGroup1.add(txtMale);
        txtMale.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMale.setText("Male");
        jPanel1.add(txtMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 320, -1));

        txtSubject.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selected--", "JEE", "DDD", "PHP" }));
        jPanel1.add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 150, -1));

        txtGame.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtGame.setText("Gaming");
        jPanel1.add(txtGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        txtRead.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtRead.setText("Reading");
        jPanel1.add(txtRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        txtWrite.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtWrite.setText("Writing");
        jPanel1.add(txtWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        // TODO add your handling code here:
        String name = txtName1.getText();
        String fatherName = txtFather.getText();
        String motherName = txtMother1.getText();
        String phone = txtPhone.getText();
        String  gender =" ";
        if(txtMale.isSelected()){
            gender="Male";
        }
        else if (txtFemale.isSelected()){
            gender="Female";
        }
        
        String date = txtDate.getDate().toString();
        String subject = txtSubject.getSelectedItem().toString();
        
        List<String> hobby = new ArrayList<>();
        if(txtRead.isSelected()){
            hobby.add("Reading");
        }
        if(txtWrite.isSelected()){
            hobby.add("Writing");
        }
        if(txtGame.isSelected()){
            hobby.add("Gaming");
        }
        
        try {
            PrintWriter write = new PrintWriter("Student.txt");
            write.print(" Name           : "+name+"\n");
            write.print(" Father's Name  : "+fatherName+"\n");
            write.print(" Mother's Name  : "+motherName+"\n");
            write.print(" Phone No       : "+phone+"\n");
            write.print(" Gender         : "+gender+"\n");
            write.print(" Date of Birth  : "+date+"\n");
            write.print(" Subject        : "+subject+"\n");
            write.print(" Hobby          : "+hobby);
            write.close();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSubmitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtFather;
    private javax.swing.JRadioButton txtFemale;
    private javax.swing.JCheckBox txtGame;
    private javax.swing.JRadioButton txtMale;
    private javax.swing.JTextField txtMother1;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JCheckBox txtRead;
    private javax.swing.JComboBox<String> txtSubject;
    private javax.swing.JCheckBox txtWrite;
    // End of variables declaration//GEN-END:variables
}
